line-length = 120
indent-width = 4

[format]
indent-style = "space"
quote-style = "double"
line-ending = "lf"
skip-magic-trailing-comma = true
docstring-code-format = true
docstring-code-line-length = 120

[lint.isort]
split-on-trailing-comma = false
