-- # -----------------------------------------------------
-- # Main Hyprland Config
-- # -----------------------------------------------------
-- # --- Environment Variables ---
-- # (You might have these in a separate file like scripts/env.sh, # but if they are here, leave them at the top)
-- # env = HYPRCURSOR_THEME,Sweet-cursors
-- # env = HYPRCURSOR_SIZE,20

-- dofile(os.getenv("HOME") .. "/.config/hypr/noctalia/noctalia-colors.conf")

-- # ...etc
-- # -- Variables para que Hyprland arranque bien desde SDDM
hl.env("XDG_CURRENT_DESKTOP","Hyprland")
hl.env("XDG_SESSION_TYPE","wayland")
hl.env("XDG_SESSION_DESKTOP","Hyprland")
hl.env("QT_QPA_PLATFORM,wayland","xcb")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION","1")
-- # Sanitize Scaling for GTK/Wayland Apps
hl.env("GDK_BACKEND,wayland,x1",",*")
hl.env("QT_QPA_PLATFORM,wayland","xcb")
hl.env("MOZ_ENABLE_WAYLAND","1")
-- # Force a specific scale if Zen looks too big/small
-- # 1 is standard, 1.25 or 1.5 for high-DPI
-- # --- THE FIX: Source Theme and Colors FIRST ---
-- # This line MUST come before any file that uses color variables.
-- # require("noctalia.noctalia-colors.lua")
-- # dofile(os.getenv("HOME") .. "/.cache/theme/hyprland_colors.lua")
-- # --- Source Monitor and Workspace Configs ---
-- # Monitor config generated by nwg-displays
--# --- Source All Configuration Files in 'conf/' ---
require("conf.startup")
require("conf.input")
require("conf.general")
require("conf.aesthetics")
require("conf.animations")
require("conf.binds")
require("conf.window")
