-- Generated by Noctalia (with dynamic cache loading)

local colors_path = os.getenv("HOME") .. "/.cache/noctalia/hyprland-colors.lua"
pcall(dofile, colors_path)

local primary = primary or "rgb(c2c1ff)"
local surface = surface or "rgb(131318)"
local on_surface = on_surface or "rgb(e4e1e9)"
local secondary = secondary or "rgb(c6c4dd)"
local on_secondary = on_secondary or "rgb(2f2f42)"
local error = error_col or "rgb(ffb4ab)"
local on_error = on_surface or "rgb(690005)"

local function apply_theme()
    hl.config({
        general = {
            col = {
                active_border = primary,
                inactive_border = surface,
            },
        },
        group = {
            col = {
                border_active = secondary,
                border_inactive = surface,
                border_locked_active = error,
                border_locked_inactive = surface,
            },

            groupbar = {
                col = {
                    active = secondary,
                    inactive = surface,
                    locked_active = error,
                    locked_inactive = surface,
                },
                text_color = on_secondary,
                text_color_inactive = on_surface,
                text_color_locked_active = on_error,
                text_color_locked_inactive = on_surface,
            },
        },
    })
end

return {
    colors = {
        primary = primary,
        surface = surface,
        on_surface = on_surface,
        secondary = secondary,
        on_secondary = on_secondary,
        error = error,
        on_error = on_error,
    },
    apply_theme = apply_theme
}
