color0 #0c1731
color1 #fd4663
color2 #678ce4
color3 #745cd6
color4 #b25cd6
color5 #93adec
color6 #a696e9
color7 #f2f2f3
color8 #5f6473
color9 #fd4663
color10 #678ce4
color11 #745cd6
color12 #b25cd6
color13 #93adec
color14 #a696e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #0c1731
background            #0c1731
foreground            #f2f2f3
selection_foreground  #afb1b6
selection_background  #111f41
active_border_color   #678ce4
inactive_border_color #111f41
url_color             #678ce4

active_tab_foreground   #181c25
active_tab_background   #678ce4
inactive_tab_foreground #afb1b6
inactive_tab_background #111f41
cursor_trail_color      #afb1b6
