color0 #1d1b22
color1 #fd4663
color2 #8467e4
color3 #b55cd6
color4 #cc66b5
color5 #a793ec
color6 #d296e9
color7 #f2f2f3
color8 #69647a
color9 #fd4663
color10 #8467e4
color11 #b55cd6
color12 #cc66b5
color13 #a793ec
color14 #d296e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1d1b22
background            #1d1b22
foreground            #f2f2f3
selection_foreground  #b0afb6
selection_background  #26242d
active_border_color   #8467e4
inactive_border_color #26242d
url_color             #8467e4

active_tab_foreground   #1b1825
active_tab_background   #8467e4
inactive_tab_foreground #b0afb6
inactive_tab_background #26242d
cursor_trail_color      #b0afb6
