color0 #14172a
color1 #fd4663
color2 #6779e4
color3 #895cd6
color4 #bd66cc
color5 #93a0ec
color6 #b496e9
color7 #f2f2f3
color8 #616476
color9 #fd4663
color10 #6779e4
color11 #895cd6
color12 #bd66cc
color13 #93a0ec
color14 #b496e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #14172a
background            #14172a
foreground            #f2f2f3
selection_foreground  #afb0b6
selection_background  #1a1e37
active_border_color   #6779e4
inactive_border_color #1a1e37
url_color             #6779e4

active_tab_foreground   #181a25
active_tab_background   #6779e4
inactive_tab_foreground #afb0b6
inactive_tab_background #1a1e37
cursor_trail_color      #afb0b6
