#!/bin/bash
# ==============================================================================
# SAVIOUR GUNDAM (Lenovo E41-55) BROWSER OPTIMIZER & THEME SYNC
# Vega 3 VCN 1.0 VA-API Acceleration + Noctalia Rice Integration
# Works across Fedora 44 & Arch Linux (Zen Browser + Firefox)
# ==============================================================================

set -euo pipefail

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[BROWSER]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_err() { echo -e "${RED}[ERROR]${NC} $1"; }

clean_browsers() {
    log_warn "Purging stale browser profiles, caches, and legacy configs..."
    killall zen-bin zen-browser firefox firefox-bin 2>/dev/null || true
    sleep 1

    # Remove profile configs and caches
    rm -rf \
        "$HOME/.zen" \
        "$HOME/.config/zen" \
        "$HOME/.cache/zen" \
        "$HOME/.mozilla" \
        "$HOME/.config/mozilla" \
        "$HOME/.cache/mozilla" \
        "$HOME/.cache/noctalia/zen-browser" \
        "$HOME/.cache/wal" 2>/dev/null || true

    log_info "Clean wipe completed. System is ready for fresh browser installation."
}

tune_profile() {
    local prof="$1"
    local browser_name="$2"
    local user_js="$prof/user.js"

    touch "$user_js"
    sed -i \
        -e '/media\.av1\.enabled/d' \
        -e '/media\.ffmpeg\.vaapi\.enabled/d' \
        -e '/media\.hardware-video-decoding\.enabled/d' \
        -e '/gfx\.webrender\.all/d' \
        -e '/widget\.use-aspect-ratio/d' \
        -e '/toolkit\.legacyUserProfileCustomizations\.stylesheets/d' \
        -e '/svg\.context-properties\.content\.enabled/d' \
        "$user_js" 2>/dev/null || true

    cat << 'EOF' >> "$user_js"
// Generated by Patata Dotfiles (Lenovo E41-55 Vega 3 tuning)
user_pref("media.av1.enabled", false);
user_pref("media.ffmpeg.vaapi.enabled", true);
user_pref("media.hardware-video-decoding.enabled", true);
user_pref("gfx.webrender.all", true);
user_pref("widget.use-aspect-ratio", true);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("svg.context-properties.content.enabled", true);
EOF
    log_info "Configured Vega 3 acceleration & CSS styling for $browser_name profile: $(basename "$prof")"
}

tune_all_browsers() {
    log_info "Applying Vega 3 VCN 1.0 hardware acceleration (VP9/H.264 VA-API, WebRender, no-CPU-AV1)..."
    local found=0

    # Scan Zen profiles
    for base in "$HOME/.config/zen" "$HOME/.zen"; do
        if [ -d "$base" ]; then
            for p in "$base"/*/; do
                if [ -d "$p" ] && [[ "$p" =~ \.(default|Default) ]]; then
                    tune_profile "$p" "Zen"
                    found=1
                fi
            done
        fi
    done

    # Scan Firefox profiles
    for base in "$HOME/.config/mozilla/firefox" "$HOME/.mozilla/firefox"; do
        if [ -d "$base" ]; then
            for p in "$base"/*/; do
                if [ -d "$p" ] && [[ "$p" =~ \.(default|Default) ]]; then
                    tune_profile "$p" "Firefox"
                    found=1
                fi
            done
        fi
    done

    if [ "$found" -eq 0 ]; then
        log_warn "No initialized browser profiles found yet. Please launch Zen and Firefox once to generate initial profiles."
    fi
}

apply_themes() {
    log_info "Synchronizing Noctalia dynamic palette with browsers..."

    # Noctalia community template for Zen Browser
    local zen_apply="$HOME/.local/state/noctalia/community-templates/zen-browser/apply.sh"
    if [ -f "$zen_apply" ]; then
        bash "$zen_apply" 2>/dev/null || true
        log_info "Applied Noctalia theme to Zen Browser userChrome.css"
    fi

    # Native Pywalfox registration for Firefox
    if command -v pywalfox &>/dev/null; then
        pywalfox install 2>/dev/null || true
        log_info "Registered Pywalfox native messaging host for Firefox"
    fi

    # Request Noctalia IPC to re-render all configured community templates
    if command -v noctalia &>/dev/null; then
        noctalia msg templates-apply 2>/dev/null || true
        log_info "Triggered Noctalia templates-apply via IPC"
    fi
}

case "${1:-all}" in
    --clean|clean)
        clean_browsers
        ;;
    --tune|tune)
        tune_all_browsers
        ;;
    --theme|theme)
        apply_themes
        ;;
    all)
        tune_all_browsers
        apply_themes
        ;;
    *)
        echo "Usage: $0 [--clean | --tune | --theme | all]"
        exit 1
        ;;
esac
