# General
general {
    gaps_in = 2
    gaps_out = 4
    border_size = 1

    col.active_border = $color4
    col.inactive_border = $color0

    layout = dwindle
}

dwindle {
    preserve_split = yes
    #smart_split = true
}

misc {
    force_default_wallpaper = 0
}

scrolling {
    fullscreen_on_one_column = true
    column_width = 0.9
    direction = right
}
workspace = 2, layout:scrolling
